name: CI-CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v3
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'  
      - name: Install dependencies
        run: dotnet restore Api/Iris.Api/Iris.Api.csproj
      - name: Build
        run: dotnet build Api/Iris.Api/Iris.Api.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test Api/Iris.Test/Iris.Test.csproj --no-restore
      
      - name: Checkout repo
        uses: actions/checkout@v3       
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1      
                       
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR        
        run: |
          docker build -f Api/Iris.Api/Dockerfile -t 270651056977.dkr.ecr.us-east-1.amazonaws.com/irisapi:latest .
          docker push 270651056977.dkr.ecr.us-east-1.amazonaws.com/irisapi:latest
    
    
      
      
      
